/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_timestamped_data_service       19
#define gattdb_emg_continous_measurement      21
#define gattdb_pulse_continous_measurement    24
#define gattdb_sa02_continous_measurement     27
#define gattdb_timestamp                      30
#define gattdb_current_time_service           32
#define gattdb_current_time                   34
#define gattdb_local_time_information         37
#define gattdb_reference_time_information     39
#define gattdb_reference_time_update_service  40
#define gattdb_time_update_control_point      42
#define gattdb_time_update_state              44
#define gattdb_battery_service_0              45
#define gattdb_battery_level                  47
#define gattdb_characteristic_presentation_format 48
#define gattdb_ota                            49
#define gattdb_ota_control                    51


#endif // __GATT_DB_H
